#PID参数
Kp: 3.0
Ki: 0.7
Kd: 0.3
#Derivative low-pass filter time constant
tau: 0.02
#Output limits (pid->out)
limMin: -1.5
limMax: 1.5
#Integrator limits
limMinInt: -3
limMaxInt: 3
# Sample time
T: 0.05
#用于检测小车停止
limvel: 0.5
#takeof vel 
takeof_vel: 0.2
front_vel: 0.2
#系数
coff: 0.0026
